// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/calc.proto

/*
Package calc is a generated protocol buffer package.

It is generated from these files:
	proto/calc.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	AddRequest
	AddReply
*/
package calc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddRequest struct {
	Num1 int64 `protobuf:"varint,1,opt,name=num1" json:"num1,omitempty"`
	Num2 int64 `protobuf:"varint,2,opt,name=num2" json:"num2,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddRequest) GetNum1() int64 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *AddRequest) GetNum2() int64 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type AddReply struct {
	Result int64 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *AddReply) Reset()                    { *m = AddReply{} }
func (m *AddReply) String() string            { return proto.CompactTextString(m) }
func (*AddReply) ProtoMessage()               {}
func (*AddReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddReply) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "calc.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "calc.HelloReply")
	proto.RegisterType((*AddRequest)(nil), "calc.AddRequest")
	proto.RegisterType((*AddReply)(nil), "calc.AddReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Calc service

type CalcClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error)
}

type calcClient struct {
	cc *grpc.ClientConn
}

func NewCalcClient(cc *grpc.ClientConn) CalcClient {
	return &calcClient{cc}
}

func (c *calcClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/calc.Calc/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error) {
	out := new(AddReply)
	err := grpc.Invoke(ctx, "/calc.Calc/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Calc service

type CalcServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	Add(context.Context, *AddRequest) (*AddReply, error)
}

func RegisterCalcServer(s *grpc.Server, srv CalcServer) {
	s.RegisterService(&_Calc_serviceDesc, srv)
}

func _Calc_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.Calc/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calc_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.Calc/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calc.Calc",
	HandlerType: (*CalcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Calc_SayHello_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Calc_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/calc.proto",
}

func init() { proto.RegisterFile("proto/calc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x8f, 0x82, 0x40,
	0x10, 0x85, 0x8f, 0x83, 0x70, 0xdc, 0xc4, 0x18, 0x32, 0x85, 0x21, 0x54, 0x66, 0x0b, 0xa3, 0x0d,
	0xc6, 0xd5, 0x3f, 0x40, 0x6c, 0xac, 0xf1, 0x17, 0xac, 0xec, 0xc6, 0x66, 0x10, 0x64, 0xa1, 0xe0,
	0xdf, 0x1b, 0x26, 0x8b, 0x62, 0xf7, 0xe6, 0xed, 0x37, 0x2f, 0x6f, 0x07, 0xe2, 0xa6, 0xad, 0xbb,
	0x7a, 0x5f, 0x2a, 0x2a, 0x33, 0x96, 0x18, 0x8c, 0x5a, 0x08, 0x58, 0x5c, 0x0c, 0x51, 0x5d, 0x98,
	0x67, 0x6f, 0x6c, 0x87, 0x08, 0xc1, 0x43, 0x55, 0x26, 0xf1, 0xd6, 0xde, 0xf6, 0xbf, 0x60, 0x2d,
	0x36, 0x00, 0x8e, 0x69, 0x68, 0xc0, 0x04, 0xfe, 0x2a, 0x63, 0xad, 0xba, 0x4f, 0xd0, 0x34, 0x8a,
	0x13, 0x40, 0xae, 0xf5, 0x3c, 0xa9, 0xaf, 0x0e, 0x0c, 0xf9, 0x05, 0x6b, 0xe7, 0xc9, 0xe4, 0xf7,
	0xed, 0x49, 0x21, 0x20, 0xe2, 0xad, 0x31, 0x7b, 0x05, 0x61, 0x6b, 0x6c, 0x4f, 0x9d, 0xdb, 0x72,
	0x93, 0x34, 0x10, 0x9c, 0x15, 0x95, 0x28, 0x21, 0xba, 0xaa, 0x81, 0xcb, 0x20, 0x66, 0xfc, 0x99,
	0x79, 0xfb, 0x34, 0xfe, 0xf2, 0x1a, 0x1a, 0xc4, 0x0f, 0xee, 0xc0, 0xcf, 0xb5, 0x46, 0xf7, 0xf4,
	0x29, 0x98, 0x2e, 0x67, 0x0e, 0xa3, 0xb7, 0x90, 0x2f, 0x73, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xf4, 0x2a, 0xd6, 0x07, 0x2d, 0x01, 0x00, 0x00,
}
