// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calc/calc.proto

/*
Package calc is a generated protocol buffer package.

It is generated from these files:
	calc/calc.proto

It has these top-level messages:
	AddRequest
	AddReply
	SubRequest
	SubReply
	MultRequest
	MultReply
	DivRequest
	DivReply
	LoginRequest
	LoginReply
*/
package calc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddRequest struct {
	Num1 int64 `protobuf:"varint,1,opt,name=num1" json:"num1,omitempty"`
	Num2 int64 `protobuf:"varint,2,opt,name=num2" json:"num2,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddRequest) GetNum1() int64 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *AddRequest) GetNum2() int64 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type AddReply struct {
	Result int64 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *AddReply) Reset()                    { *m = AddReply{} }
func (m *AddReply) String() string            { return proto.CompactTextString(m) }
func (*AddReply) ProtoMessage()               {}
func (*AddReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddReply) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type SubRequest struct {
	Num1 int64 `protobuf:"varint,1,opt,name=num1" json:"num1,omitempty"`
	Num2 int64 `protobuf:"varint,2,opt,name=num2" json:"num2,omitempty"`
}

func (m *SubRequest) Reset()                    { *m = SubRequest{} }
func (m *SubRequest) String() string            { return proto.CompactTextString(m) }
func (*SubRequest) ProtoMessage()               {}
func (*SubRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SubRequest) GetNum1() int64 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *SubRequest) GetNum2() int64 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type SubReply struct {
	Result int64 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *SubReply) Reset()                    { *m = SubReply{} }
func (m *SubReply) String() string            { return proto.CompactTextString(m) }
func (*SubReply) ProtoMessage()               {}
func (*SubReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SubReply) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MultRequest struct {
	Num1 int64 `protobuf:"varint,1,opt,name=num1" json:"num1,omitempty"`
	Num2 int64 `protobuf:"varint,2,opt,name=num2" json:"num2,omitempty"`
}

func (m *MultRequest) Reset()                    { *m = MultRequest{} }
func (m *MultRequest) String() string            { return proto.CompactTextString(m) }
func (*MultRequest) ProtoMessage()               {}
func (*MultRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MultRequest) GetNum1() int64 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *MultRequest) GetNum2() int64 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type MultReply struct {
	Result int64 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *MultReply) Reset()                    { *m = MultReply{} }
func (m *MultReply) String() string            { return proto.CompactTextString(m) }
func (*MultReply) ProtoMessage()               {}
func (*MultReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MultReply) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type DivRequest struct {
	Num1 int64 `protobuf:"varint,1,opt,name=num1" json:"num1,omitempty"`
	Num2 int64 `protobuf:"varint,2,opt,name=num2" json:"num2,omitempty"`
}

func (m *DivRequest) Reset()                    { *m = DivRequest{} }
func (m *DivRequest) String() string            { return proto.CompactTextString(m) }
func (*DivRequest) ProtoMessage()               {}
func (*DivRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DivRequest) GetNum1() int64 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *DivRequest) GetNum2() int64 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type DivReply struct {
	Result int64 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *DivReply) Reset()                    { *m = DivReply{} }
func (m *DivReply) String() string            { return proto.CompactTextString(m) }
func (*DivReply) ProtoMessage()               {}
func (*DivReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DivReply) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type LoginRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Pwd  string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type LoginReply struct {
	Wellcome string `protobuf:"bytes,1,opt,name=wellcome" json:"wellcome,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *LoginReply) GetWellcome() string {
	if m != nil {
		return m.Wellcome
	}
	return ""
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "calc.AddRequest")
	proto.RegisterType((*AddReply)(nil), "calc.AddReply")
	proto.RegisterType((*SubRequest)(nil), "calc.SubRequest")
	proto.RegisterType((*SubReply)(nil), "calc.SubReply")
	proto.RegisterType((*MultRequest)(nil), "calc.MultRequest")
	proto.RegisterType((*MultReply)(nil), "calc.MultReply")
	proto.RegisterType((*DivRequest)(nil), "calc.DivRequest")
	proto.RegisterType((*DivReply)(nil), "calc.DivReply")
	proto.RegisterType((*LoginRequest)(nil), "calc.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "calc.LoginReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Calc service

type CalcClient interface {
	// define calc function
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error)
	Sub(ctx context.Context, in *SubRequest, opts ...grpc.CallOption) (*SubReply, error)
	Mult(ctx context.Context, in *MultRequest, opts ...grpc.CallOption) (*MultReply, error)
	Div(ctx context.Context, in *DivRequest, opts ...grpc.CallOption) (*DivReply, error)
	Login(ctx context.Context, opts ...grpc.CallOption) (Calc_LoginClient, error)
}

type calcClient struct {
	cc *grpc.ClientConn
}

func NewCalcClient(cc *grpc.ClientConn) CalcClient {
	return &calcClient{cc}
}

func (c *calcClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error) {
	out := new(AddReply)
	err := grpc.Invoke(ctx, "/calc.Calc/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Sub(ctx context.Context, in *SubRequest, opts ...grpc.CallOption) (*SubReply, error) {
	out := new(SubReply)
	err := grpc.Invoke(ctx, "/calc.Calc/Sub", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Mult(ctx context.Context, in *MultRequest, opts ...grpc.CallOption) (*MultReply, error) {
	out := new(MultReply)
	err := grpc.Invoke(ctx, "/calc.Calc/Mult", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Div(ctx context.Context, in *DivRequest, opts ...grpc.CallOption) (*DivReply, error) {
	out := new(DivReply)
	err := grpc.Invoke(ctx, "/calc.Calc/Div", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Login(ctx context.Context, opts ...grpc.CallOption) (Calc_LoginClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Calc_serviceDesc.Streams[0], c.cc, "/calc.Calc/Login", opts...)
	if err != nil {
		return nil, err
	}
	x := &calcLoginClient{stream}
	return x, nil
}

type Calc_LoginClient interface {
	Send(*LoginRequest) error
	CloseAndRecv() (*LoginReply, error)
	grpc.ClientStream
}

type calcLoginClient struct {
	grpc.ClientStream
}

func (x *calcLoginClient) Send(m *LoginRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calcLoginClient) CloseAndRecv() (*LoginReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LoginReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Calc service

type CalcServer interface {
	// define calc function
	Add(context.Context, *AddRequest) (*AddReply, error)
	Sub(context.Context, *SubRequest) (*SubReply, error)
	Mult(context.Context, *MultRequest) (*MultReply, error)
	Div(context.Context, *DivRequest) (*DivReply, error)
	Login(Calc_LoginServer) error
}

func RegisterCalcServer(s *grpc.Server, srv CalcServer) {
	s.RegisterService(&_Calc_serviceDesc, srv)
}

func _Calc_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.Calc/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calc_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.Calc/Sub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Sub(ctx, req.(*SubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calc_Mult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Mult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.Calc/Mult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Mult(ctx, req.(*MultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calc_Div_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DivRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Div(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.Calc/Div",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Div(ctx, req.(*DivRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calc_Login_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalcServer).Login(&calcLoginServer{stream})
}

type Calc_LoginServer interface {
	SendAndClose(*LoginReply) error
	Recv() (*LoginRequest, error)
	grpc.ServerStream
}

type calcLoginServer struct {
	grpc.ServerStream
}

func (x *calcLoginServer) SendAndClose(m *LoginReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calcLoginServer) Recv() (*LoginRequest, error) {
	m := new(LoginRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Calc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calc.Calc",
	HandlerType: (*CalcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Calc_Add_Handler,
		},
		{
			MethodName: "Sub",
			Handler:    _Calc_Sub_Handler,
		},
		{
			MethodName: "Mult",
			Handler:    _Calc_Mult_Handler,
		},
		{
			MethodName: "Div",
			Handler:    _Calc_Div_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Login",
			Handler:       _Calc_Login_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "calc/calc.proto",
}

func init() { proto.RegisterFile("calc/calc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4e, 0xbb, 0x40,
	0x10, 0xc6, 0xe1, 0x0f, 0xff, 0xa6, 0x8c, 0xc6, 0xe2, 0x1c, 0x4c, 0xc3, 0xc9, 0xac, 0x17, 0x4c,
	0x4c, 0x4d, 0x51, 0x1f, 0xa0, 0xb1, 0x47, 0xbd, 0xd0, 0x27, 0x00, 0x76, 0x63, 0x48, 0xb6, 0x05,
	0x5b, 0xb6, 0x4d, 0xdf, 0xd8, 0xc7, 0x30, 0x3b, 0xb0, 0xb0, 0x5e, 0x6a, 0xec, 0x85, 0xcc, 0x7e,
	0x3b, 0xdf, 0x2f, 0xc3, 0x7c, 0x0b, 0x93, 0x22, 0x93, 0xc5, 0xa3, 0xfe, 0xcc, 0xea, 0x6d, 0xd5,
	0x54, 0xe8, 0xeb, 0x9a, 0x3d, 0x03, 0x2c, 0x38, 0x4f, 0xc5, 0xa7, 0x12, 0xbb, 0x06, 0x11, 0xfc,
	0x8d, 0x5a, 0xcf, 0xa7, 0xee, 0xad, 0x1b, 0x7b, 0x29, 0xd5, 0x9d, 0x96, 0x4c, 0xff, 0xf5, 0x5a,
	0xc2, 0x18, 0x8c, 0xc9, 0x55, 0xcb, 0x23, 0xde, 0xc0, 0x68, 0x2b, 0x76, 0x4a, 0x36, 0x9d, 0xab,
	0x3b, 0x69, 0xf2, 0x4a, 0xe5, 0x67, 0x90, 0xc9, 0x75, 0x8a, 0xfc, 0x02, 0x17, 0xef, 0x4a, 0x36,
	0x7f, 0x45, 0xdf, 0x41, 0xd0, 0xda, 0x7e, 0x99, 0x7a, 0x59, 0xee, 0xcf, 0x98, 0x9a, 0x5c, 0xa7,
	0xc9, 0x97, 0x6f, 0xd5, 0x47, 0xb9, 0xb1, 0xd9, 0xd9, 0x5a, 0x50, 0x57, 0x90, 0x52, 0x8d, 0x21,
	0x78, 0xf5, 0x81, 0x13, 0x3a, 0x48, 0x75, 0xc9, 0x62, 0x80, 0xce, 0xa5, 0xd9, 0x11, 0x8c, 0x0f,
	0x42, 0xca, 0xa2, 0xea, 0x7d, 0xfd, 0x39, 0xf9, 0x72, 0xc1, 0x7f, 0xcd, 0x64, 0x81, 0xf7, 0xe0,
	0x2d, 0x38, 0xc7, 0x70, 0x46, 0x61, 0x0f, 0xe9, 0x46, 0x57, 0x96, 0x52, 0xcb, 0x23, 0x73, 0x74,
	0xeb, 0x4a, 0xe5, 0xa6, 0x75, 0x88, 0xcb, 0xb4, 0x9a, 0x28, 0x98, 0x83, 0x0f, 0xe0, 0xeb, 0xed,
	0xe1, 0x75, 0x7b, 0x63, 0x05, 0x10, 0x4d, 0x6c, 0xa9, 0x07, 0x2f, 0xcb, 0xbd, 0x01, 0x0f, 0x1b,
	0x35, 0x60, 0xb3, 0x2d, 0xe6, 0xe0, 0x1c, 0xfe, 0xd3, 0x1f, 0x22, 0xb6, 0x57, 0xf6, 0x92, 0xa2,
	0xf0, 0x87, 0x46, 0x86, 0xd8, 0xcd, 0x47, 0xf4, 0x82, 0x9f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xf3, 0x3e, 0x44, 0x28, 0xd4, 0x02, 0x00, 0x00,
}
